### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by eshansingh** [paoloantinori/hhighlighter#11]
No, seriously. I copied `h.sh` into `~/h.sh`. I have installed ack via Homebrew on OSX 10.11.3 (note - that's a beta version of OSX), and it's working:

```
ack 2.14
Running under Perl 5.22.1 at /opt/local/bin/perl5.22

Copyright 2005-2014 Andy Lester.

This program is free software.  You may modify or distribute it
under the terms of the Artistic License v2.0.
```

Then I added the following line to my `~/.zshrc`:

```
. ~/h.sh
```

Then I did this to test it out:

```
$ tail -f /var/log/system.log | h System
```

Which gave this:

```
usage: YOUR_COMMAND | h [-idn] args...
    -i : ignore case
    -d : disable regexp
    -n : invert colors
```

**Comment by mperry2** [comment]
What version of zsh are you using?

**Comment by eshansingh** [comment]
`zsh 5.0.8 (x86_64-apple-darwin15.0)`

**Comment by paoloantinori** [comment]
I don't have a MacOSX for testing. Can you try to set debugging on for the shell session with `setopt XTRACE VERBOSE` and retry. Hopefully we could get some extra hint.

**Comment by eshansingh** [comment]
I ran `setopt XTRACE VERBOSE` and then ran `tail -f /var/log/system.log | h System` again. The output is:

```
tail -f /var/log/system.log | h System
+omz_termsupport_preexec:1> emulate -L zsh
+omz_termsupport_preexec:2> setopt extended_glob
+omz_termsupport_preexec:4> [[ '' == true ]]
+omz_termsupport_preexec:9> local 'CMD=tail'
+omz_termsupport_preexec:10> local 'LINE=tail -f /var/log/system.log | fc -El 1 System'
+omz_termsupport_preexec:12> title '$CMD' '%100>...>$LINE%<<'
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%100>...>$LINE%<<'
+title:10> case xterm-256color (cygwin | xterm*)
+title:12> print -Pn '\e]2;%100\>...\>\$LINE%\<\<\a'
+title:13> print -Pn '\e]1;\$CMD\a'
+-zsh:4> fc -El 1 System
+-zsh:4> tail -f /var/log/system.log
+fc:9> local _OPTS
+fc:12> test -t 0
+fc:18> getopts :idnQ opt
+fc:19> case ? (i)
+fc:19> case ? (d)
+fc:19> case ? (n)
+fc:19> case ? (Q)
+fc:19> case ? (\?)
+fc:25> _usage
+_usage:1> echo 'usage: YOUR_COMMAND | h [-idn] args...
    -i : ignore case
    -d : disable regexp
    -n : invert colors'
usage: YOUR_COMMAND | h [-idn] args...
    -i : ignore case
    -d : disable regexp
    -n : invert colors
+fc:26> return
+omz_termsupport_precmd:1> emulate -L zsh
+omz_termsupport_precmd:3> [[ '' == true ]]
+omz_termsupport_precmd:7> title '%15<..<%~%<<' '%n@%m: %~'
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%n@%m: %~'
+title:10> case xterm-256color (cygwin | xterm*)
+title:12> print -Pn '\e]2;%n@%m:\ %~\a'
+title:13> print -Pn '\e]1;%15\<..\<%~%\<\<\a'
+_z_precmd:1> _z --add /Users/eshan
+_z:2> local 'datafile=/Users/eshan/.z'
+_z:5> [ -z '' -a -f /Users/eshan/.z -a '!' -O /Users/eshan/.z ']'
+_z:8> [ --add '=' --add ']'
+_z:9> shift
+_z:12> [ /Users/eshan '=' /Users/eshan ']'
+_z:12> return
+-zsh:5> ys_hg_prompt_info
+ys_hg_prompt_info:2> [ -d .hg ']'
+-zsh:5> git_prompt_info
+git_prompt_info:1> local ref
+git_prompt_info:2> [[+git_prompt_info:2> git config --get oh-my-zsh.hide-status
+git_prompt_info:2> [[ '' != 1 ]]
+git_prompt_info:3> ref=+git_prompt_info:3> git symbolic-ref HEAD
+git_prompt_info:3> ref=''
+git_prompt_info:4> ref=+git_prompt_info:4> git rev-parse --short HEAD
+git_prompt_info:4> ref=''
+git_prompt_info:4> return 0
```

**Comment by desyncr** [comment]
There is a problem with OMZ's [history plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/history/history.plugin.zsh).

You should disable that and see if the problem persist.

Good luck!

**Comment by coresh** [comment]
### The similar issue:
    $ ls -la | h admin
    usage: YOUR_COMMAND | h [-idn] args...
        -i : ignore case
        -d : disable regexp
        -n : invert colors

        $ zsh --version
        zsh 5.2 (x86_64-redhat-linux-gnu)

        $ uname -a
        Linux localhost.localdomain 4.9.5-200.fc25.x86_64 #1 SMP Fri Jan 20 12:24:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by desyncr** [comment]
@coresh Could you provide your zsh config? Tried same command locally and works as expected:

    △ ~ zsh --version                   
    zsh 5.2 (x86_64-redhat-linux-gnu)

    ▲ ~ uname -a
    Linux hp-envy 4.8.10-300.fc25.x86_64 #1 SMP Mon Nov 21 18:59:16 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by coresh** [comment]
@desyncr 
http://pastebin.com/YZ7PDiYy

**Comment by desyncr** [comment]
@coresh Well, it's the same problem I just described [above your comment](https://github.com/paoloantinori/hhighlighter/issues/11#issuecomment-241237590).

    > type h
    h is an alias for history

    > unalias h
    > source hhighlighting/h.sh
    > echo hello | h he
    hello

**Comment by coresh** [comment]
@desyncr Thanks: exactly!
