### ISSUE TITLE
piping with less

### ISSUE THREAD

**Issue by suewonjp** [paoloantinori/hhighlighter#13]
First of all...very good tool!

This might be a known limitation, but when I do like this

    cat LICENSE.txt | h copyright | less

It displays like that: (just color encodings shown instead of colors)

    "Licensor" shall mean the ESC[4;1;31mcopyrightESC[0m owner or entity authorized byESC[0mESC[K
      the ESC[4;1;31mcopyrightESC[0m owner that is granting the License.ESC[0mESC[K

I'm just curious, supporting _less_ would be quite a challenge or is it feasible?

**Comment by paoloantinori** [comment]
Hi, the support that you are looking for is actually in `less`.

try either `cat LICENSE.txt | h copyright a b c | \less -r` or `cat LICENSE.txt | h copyright a b c | \less -R`

**Comment by suewonjp** [comment]
Cool... 😀

Thanks a lot...
