### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by psprint** [paoloantinori/hhighlighter#16]
I installed it on Zsh using Zplugin:

```zsh
zplg ice as"command" cp"h.sh -> h" pick"h"
zplg load paoloantinori/hhighlighter
```

But running the examples, also after the example `export` commands, yields empty output. I tried changing `#!/bin/bash` to `#!/usr/local/bin/bash` to use OS X Homebrew Bash 4.4, but no improvement. Maybe the command doesn't support OS X?

**Comment by paoloantinori** [comment]
Hi, I don't have access to a MacOS to test it on that platform.

Have you tried testing it in bash and not in zsh?

**Comment by desyncr** [comment]
Can confirm it works on MacOS.
```
 ▲ ~ zsh --version
zsh 5.3 (x86_64-apple-darwin14.5.0)

 ▲ ~ uname -a
Darwin 14.5.0 Darwin Kernel Version 14.5.0: ...
```

**Comment by psprint** [comment]
It has resolved, I thought it is command-script, while it is a function defined in file `h.sh`. So the file should be sourced, or as README says copied to rc-file. Sorry for bothering.
