### ISSUE TITLE
Work with ack installed as ack-grep

### ISSUE THREAD

**Issue by TorKlingberg** [paoloantinori/hhighlighter#5]
I have ack installed on my Ubuntu Machine (14.04.2 LTS), but it is not installed as `ack` but as `ack-grep`. I think it is that way by default in Ubuntu to avoid a name collision with some other tool. Could `h` detect `ack-grep` and use that?

**Comment by sr105** [comment]
I issued a pull request, but in the meantime:
https://github.com/sr105/hhighlighter/commit/8c0536399a6843ccc9930e14c6142d31c268c4dd
